# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|
  # locally added archlinux64 box
  config.vm.box = "archlinux64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true

    # Customize the amount of memory on the VM:
    vb.memory = "2048"
  end

  # Install required software:
  # - xfce4
  # - gvim
  config.vm.provision "shell", inline: <<-SHELL
    pacman --noconfirm -Syu xfce4 gvim
    echo "startxfce4" > /home/vagrant/.xinitrc
    chown vagrant:vagrant /home/vagrant/.xinitrc
    /vagrant/keymap.sh
  SHELL
end
